### ISSUE TITLE
No items showing for "non indieweb" websites?

### ISSUE THREAD

**Issue by prtksxna** [jackjamieson2/yarns-microsub-server#88]
I just started using Yarns with Together (same behavior with Monocle too) and its been working perfectly for one of my channels that has the following people:

- http://tantek.com/
- https://aaronparecki.com/
- https://david.shanske.com/
- https://prtksxna.com/

However, I get no items at all for other websites (that are running WordPress) but don't have anything IndieWeb installed AFAIK, like:

- https://samwilson.id.au/
- https://arunraghavan.net/blog/
- https://nigelb.me/

Could you help me troubleshoot this?

**Comment by jackjamieson2** [comment]
Happy to help!

Can you clarify a few points?

1) For each site, which feed are you following?

    e.g. for the first site there are three feeds:
    - https://samwilson.id.au/#page
    - https://samwilson.id.au/comments/feed/
    - https://samwilson.id.au/feed/

2) Could you also try viewing your feeds in https://monocle.p3k.io?
    Together is bit stricter than Monocle. If you can see these feeds in Monocle but not in Together, then I'll document it in #89.

Thanks for the bug report!

**Comment by prtksxna** [comment]
For all the WordPress sites I am following the `/feed/`, so:
- https://nigelb.me/feed
- https://arunraghavan.net/feed/
- https://samwilson.id.au/feed/

For the ones that are working I am following a combination of different feeds:
- http://tantek.com#recent-articles
- https://aaronparecki.com/all
- https://david.shanske.com/all/
- ttps://prtksxna.com/feed/

**Comment by prtksxna** [comment]
I am getting the same behavior in Together, Monocle and Indigenous.

**Comment by jackjamieson2** [comment]
Thanks, I’ll check it out and try to figure out the problem!

**Comment by jackjamieson2** [comment]
@prtksxna, I checked out these feeds and they seem to parse correctly.

I suspect the issue is just that these sites hadn't posted in the 14 days leading up to your error report.  

By default, Yarns only fetches and stores posts from the previous 14 days. This can be changed in the "Yarns Options" section immediately below the channel list.

![Screen Shot 2019-08-06 at 12 16 18 PM](https://user-images.githubusercontent.com/12275399/62556988-128c9200-b844-11e9-87ac-9001f8ce738b.png)

It looks like https://samwilson.id.au/ had posted in the past few days so I think you should now be able to see those posts. 

When you get time, could you let me know if my hunch is correct? Thanks

**Comment by prtksxna** [comment]
You're absolutely right. I checked Indigenous in the morning as saw Sam's posts and realized what must've happened. I didn't know about that setting. Thank you so much for looking into this, and sorry that it wasn't really an issue 😅

**Comment by jackjamieson2** [comment]
Now I know that I should make that setting more apparent!
